version: '3'
services:
  db:
    container_name: izanami_db
    image: postgres:15.3
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=izanami
      - POSTGRES_PASSWORD=Hogepiyo

  web:
    container_name: izanami_web
    build:
      context: .
      args:
        RAILS_ENV: "development"
    volumes:
      - ./app:/izanami:rw
    ports:
      - "3000:3000"
    depends_on:
      - db
