version: '3'
services:
  db:
    container_name: izanami_db
    image: postgres:15.3
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=izanami
      - POSTGRES_PASSWORD=Hogepiyo

  web:
    container_name: izanami_web
    build:
      context: .
      args:
        RAILS_ENV: "development"
    volumes:
      - ./src:/izanami:rw
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    command: /bin/bash -c "rdbg --open --command -- bundle exec rails server -b 0.0.0.0 -e development"
    depends_on:
      - db
